package org.yy.dal.parse.parser;

import java.io.Reader;

import org.yy.dal.parse.CCJSqlParser;
import org.yy.dal.parse.JSQLParserException;
import org.yy.dal.parse.statement.Statement;

/**
 * A JSqlParser implementation that uses a parser generated by JavaCC
 * <一句话功能简述>
 * <功能详细描述>
 * 
 * @author  zhouliang
 * @version  [版本号, 2015年1月22日]
 * @since  [产品/模块版本]
 */
public class CCJSqlParserManager implements JSqlParser {
    
    @Override
    public Statement parse(Reader statementReader)
        throws JSQLParserException {
        CCJSqlParser parser = new CCJSqlParser(statementReader);
        try {
            return parser.Statement();
        }
        catch (Exception ex) {
            throw new JSQLParserException(ex);
        }
    }
}