/*
* 文 件 名:  PreparedStatementType.java
* 版    权:  YY Technologies Co., Ltd. Copyright 2012-2013,  All rights reserved
* 描    述:  创建PreparedStatement的模式
* 修 改 人:  zhouliang
* 修改时间:  2016年3月3日
* 修改内容:  <修改内容>
*/
package org.yy.dal.executor;

/**
* 创建PreparedStatement的模式
* 
* @author  zhouliang
* @version  [版本号, 2016年3月3日]
* @since  [产品/模块版本]
*/
public enum PreparedStatementMode {
    BASE, //prepareStatement(String sql)
    RESLUTSETTYPE_1, //prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
    RESLUTSETTYPE_2, //prepareStatement(String sql, int resultSetType, int resultSetConcurrency,int resultSetHoldability)
    AUTOGENERATEKEYS, //prepareStatement(String sql, int autoGeneratedKeys)
    COLUMNINDEXES, //prepareStatement(String sql, int[] columnIndexes)
    COLUMNNAMES //prepareStatement(String sql, String[] columnNames)
}
