/*
* 文 件 名:  YYDalStatement.java
* 版    权:  YY Technologies Co., Ltd. Copyright 2012-2013,  All rights reserved
* 描    述:  <描述>
* 修 改 人:  zhouliang
* 修改时间:  2016年3月4日
* 修改内容:  <修改内容>
*/
package org.yy.dal.ds;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.yy.dal.ds.constants.StatementMode;
import org.yy.dal.ds.support.YYDalStatementSupport;

/**
* <一句话功能简述>
* <功能详细描述>
* 
* @author  zhouliang
* @version  [版本号, 2016年3月4日]
* @since  [产品/模块版本]
*/
public class YYDalStatement extends YYDalStatementSupport implements Statement {
    
    //原始sql
    private String sql;
    
    //数据源π
    private YYDalDatasource datasource;
    
    //连接
    private YYDalConnection connection;
    
    private StatementMode model;
    
    private int reslutSetType;
    
    private int resultSetConcurrency;
    
    private int resultSetHoldability;
    
    public YYDalStatement(YYDalDatasource datasource, YYDalConnection connection) {
        this.datasource = datasource;
        this.connection = connection;
        this.model = StatementMode.BASE;
    }
    
    public YYDalStatement(YYDalDatasource datasource, YYDalConnection connection, int resultSetType,
        int resultSetConcurrency) {
        this.datasource = datasource;
        this.connection = connection;
        this.model = StatementMode.RESLUTSETTYPE_1;
        this.reslutSetType = resultSetType;
        this.resultSetConcurrency = resultSetConcurrency;
    }
    
    public YYDalStatement(YYDalDatasource datasource, YYDalConnection connection, int resultSetType,
        int resultSetConcurrency, int resultSetHoldability) {
        this.datasource = datasource;
        this.connection = connection;
        this.model = StatementMode.RESLUTSETTYPE_2;
        this.reslutSetType = resultSetType;
        this.resultSetConcurrency = resultSetConcurrency;
        this.resultSetHoldability = resultSetHoldability;
    }
    
    /** {@inheritDoc} */
    @Override
    public ResultSet executeQuery(String sql)
        throws SQLException {
        return null;
    }
    
    /** {@inheritDoc} */
    @Override
    public int executeUpdate(String sql)
        throws SQLException {
        // TODO Auto-generated method stub
        return 0;
    }
    
    /** {@inheritDoc} */
    @Override
    public void close()
        throws SQLException {
        // TODO Auto-generated method stub
        
    }
    
    /** {@inheritDoc} */
    @Override
    public boolean execute(String sql)
        throws SQLException {
        // TODO Auto-generated method stub
        return false;
    }
    
    /** {@inheritDoc} */
    @Override
    public Connection getConnection()
        throws SQLException {
        // TODO Auto-generated method stub
        return null;
    }
    
    /** {@inheritDoc} */
    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys)
        throws SQLException {
        // TODO Auto-generated method stub
        return 0;
    }
    
    /** {@inheritDoc} */
    @Override
    public int executeUpdate(String sql, int[] columnIndexes)
        throws SQLException {
        // TODO Auto-generated method stub
        return 0;
    }
    
    /** {@inheritDoc} */
    @Override
    public int executeUpdate(String sql, String[] columnNames)
        throws SQLException {
        // TODO Auto-generated method stub
        return 0;
    }
    
    /** {@inheritDoc} */
    @Override
    public boolean execute(String sql, int autoGeneratedKeys)
        throws SQLException {
        // TODO Auto-generated method stub
        return false;
    }
    
    /** {@inheritDoc} */
    @Override
    public boolean execute(String sql, int[] columnIndexes)
        throws SQLException {
        // TODO Auto-generated method stub
        return false;
    }
    
    /** {@inheritDoc} */
    @Override
    public boolean execute(String sql, String[] columnNames)
        throws SQLException {
        // TODO Auto-generated method stub
        return false;
    }
    
    /** {@inheritDoc} */
    @Override
    public boolean isClosed()
        throws SQLException {
        // TODO Auto-generated method stub
        return false;
    }
    
}
